language: python
python:
  - "2.7"
install:
  - pip install flake8
  - pip install psycopg2
  - python setup.py install
script:
  - python setup.py test
  - python setup.py test_on_postgres
  - flake8 .
notations:
  email:
      - ci-notify@openlabs.co.in
